### ISSUE TITLE
Why the silence?

### ISSUE THREAD

**Issue by vibrantBits** [tenancy/tenancy#13]
Suddenly this awsome project seems to be dormant. Is it?

**Comment by luceos** [comment]
Tenancy/tenancy is the successor of hyn/multi-tenant which already is being used by many different projects in production. While having spent several years working on hyn/multi-tenant, I decided it was time to finally finish one of my own side projects before completing this package. Because every package you maintain adds onto the pile of responsibilities.

I still plan on tagging an initial release somewhere this year, as it is already running on an end, I guess that might be in December.
