### ISSUE TITLE
Question about `identified`

### ISSUE THREAD

**Issue by mblarsen** [tenancy/tenancy#161]
https://github.com/tenancy/tenancy/blob/9b425bc31294fc529b2fbfb2e66243ef20d90afe/src/Tenancy/Environment.php#L41-L52

I'm wondering what the intend of `identified` is. Is it to tell identification has run or to tell that a tenant was identified?

```php
if (!$this->identified) { 
    $this->identified = true; 
} 
// is the same as
$this->identified = true; 
```

Anyway if `identified` means a tenant was found I guess it should be:

```php
     $this->identified = $tenant !== null
```

**Comment by fletch3555** [comment]
A fair question.  I'll add my thoughts and defer to @ArlonAntonius.

The setTenant() method is only called by identifyTenant() (yes, it's public, but I'll ignore that at the moment for the sake of argument).  identifyTenant() only calls it if `!$this->identified` (rendering the conditional redundant) or if `$refresh`.  Following the `$refresh` branch, the conditional still doesn't matter because the end result is that `$this->identified` is always true.

I recommend removing the conditional.

@mblarsen, as for your last code snippet, that's logically different as it can also set the value to `false`.

**Comment by ArlonAntonius** [comment]
Hi there,

It's meant as an indication of whether identification ran in any way. You can check if a tenant is identified based on `getTenant()` so would not really see the benefit in it reflecting the `yeah there is a tenant identified`.
