### ISSUE TITLE
Error: MailFake does not have a method "alwaysFrom"

### ISSUE THREAD

**Issue by BitTheCat** [tenancy/tenancy#257]
__Information__

- tenancy/affects/mail version: 2.x-dev
- laravel version: 9.19

I am using the latest version of affects/mails (and all the individual packages because if I use tenancy/tenancy I have a problem with the appUrl in the notification always taking localhost) and in the tests where I set Notification::fake() and Mail::fake() these fail because I get the following error:

> TypeError : call_user_func_array(): Argument #1 ($callback) must be a valid callback, class Illuminate\Support\Testing\Fakes\MailFake does not have a method "alwaysFrom"

I expect not to receive this error

**Comment by ArlonAntonius** [comment]
We do not directly call "alwaysFrom" in the package anymore. You should not be experiencing this issue anymore because of that.

We recommend checking yourself if the function exists in your listener and only applying the function if available.

If you feel like your issue has not been properly addressed yet, or if you still need more information, please reopen this issue 😄

If you require help with a different issue, please open a new issue.

You can also find Tenancy related help & resources on:
- [Our Website](https://tenancy.dev/)
- [Our Discord Server](https://tenancy.dev/chat)
