### ISSUE TITLE
What is the different?

### ISSUE THREAD

**Issue by JFOC** [tenancy/tenancy#9]
What is the different between tenancy/tenancy and  hyn/multi-tenant ?

**Comment by luceos** [comment]
Hyn is the oldest version which, for one, allows overriding some functionality per tenant website with custom config files, routes, vendor (composer compatible) folder, media and translations. The fundamental problem with this approach is that in cloud or scalable architecture these files and/or directories cannot be included from the filesystem. That's also the reason you see Hyn check whether the configured filesystem is local or not.

Taking the above in consideration, tenancy/tenancy is a cloud-first rewrite. It is aimed to be even more flexible and resolve some of the problems found in its predecessor. The greatest difference (so far) is what a tenant is and how tenant identification works. 

Hyn tells you that a Website is a Tenant, it even binds one into the Container once a related Hostname was found or once you set it as active tenant. To partially resolve that we allow you to exchange that Website model inside a configuration; that solution is not too pretty. Tenancy, on the other hand, dispatches an event to compatible listeners able to return any object implementing the Tenant trait. Instead of forcing you to use the Website you can use whatever Eloquent model you wish as long as it implements the interface. This allows you to use a Spark team or a custom model as a tenant. It also allows you to have multiple ways of identifying a tenant; using environment variables, a http request object or anything else.

The last difference is that hyn is stable, tenancy/tenancy is not.

Hope this answers your question; I guess it makes sense to add this to the documentation somewhere 😄

**Comment by JFOC** [comment]
Agreed! This one should be in the documentation.
I am assuming tenancy/tenancy is not production use ready yet.

**Comment by luceos** [comment]
> I am assuming tenancy/tenancy is not production use ready yet.

Indeed, tenancy is not close to being used by anyone; including me. An upgrade path from hyn to tenancy should be possible and I'll do my best to make that happen. So please use hyn/multi-tenant 5.2 (not 5.1).

Also check: https://www.patreon.com/posts/17012924

**Comment by JFOC** [comment]
Thank you
