### ISSUE TITLE
Issues Found While Testing

### ISSUE THREAD

**Issue by sniper7kills** [tenancy/tenancy#90]
### Host Part of Username On Remote SQL Server
When working with a database on a separate host the tenant user is unable to connect due to the host name portion of their username not matching what was created:

Local IP: 192.168.0.30
SQL IP: 192.168.0.27

When the user is created it is created as `tenant@192.168.0.27` but when connecting to the database the username is `tenant@192.168.0.30` resulting in an access denied error.
`[1045] Access denied for user 'tenant'@'192.168.0.30' (using password: YES)`

**Possible Solutions:**
Default SQL User's host to a wildcard
Allow the option for a wildcard to be used as the users host.
(Probably going to be needed in order to support Laravel vapor, and multi server setups)

### SQL `IF NOT EXISTS` in AWS Aurora Serverless MySQL
Due to AWS Aurora Serverless running MySQL version 5.6 the `IF NOT EXISTS` command doesn't exist and the user does not get created.

`Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS 'tenant'@'127.0.0.1' IDENTIFIED BY '...' `

**Possible Solutions**
Update query to be MySQL 5.6 compatible
Have an additional MySQL driver that is 5.6 compatible (Community could create)
Only Support MySQL version 5.7+

### Handling of SQL Errors
This is a relativity minor issue in my eyes as I foresee people using dedicated SQL servers for any SaaS they deploy; But if SQL throws an error and the package continue on simply logging the error.

While testing, I've forgotten to delete the database for a tenant and SQL will warn that the database already exists when going to create the database, and the package will continue to use the preexisting database.

The same happens for existing users; which may cause an issue as I believe the password does get updated which can cause problems for anything else that was using that account.

**Possible Solutions**
Make a note in documentation?

### Lifecycle Hook Queues
Currently in both `Tenancy\Lifecycle\Hook` and `Tenancy\Lifecycle\ConfigurableHook` `$queue` is intended to be the name of the queue. When changing it in a listener (Migrations for example) it type hints to `bool|null|string`. 
While not intended to be set to true, if it is, an error will be thrown that its an invalid queue.

Instead, if set to true `queue()` should return null

**Comment by ArlonAntonius** [comment]
Thanks for all your work again @sniper7kills, you've provided us with amazing help while developing this package.

> When working with a database on a separate host the tenant user is unable to connect due to the hostname portion of their username not matching what was created.

This was fixed in a PR separating the Database & Connections parts of the package in their own respective packages.
You can now listen to the Tenancy\HooksDatabase\Drivers\Configuring event which is different from the one setting the connection.

> Due to AWS Aurora Serverless running MySQL version 5.6 the IF NOT EXISTS command doesn't exist and the user does not get created.

@luceos and I had a chat about this and are not 100% sure on which direction we want to go. Hope to update you on this later.

> Handling of SQL Errors

Thanks for this, fixed it in [a commit](https://github.com/tenancy/tenancy/commit/7f9d7d824a5191cb6e8d52d95bc9dad47d440310) some time ago based on your tip :D

> Lifecycle Hook Queues

I changed the typehint of this so it would show you that you can't set it to true anymore. If you feel like we should handle this differently, let me know.
